### ISSUE TITLE
Labrador application not responding on MAC OS 11.2 Big Sur

### ISSUE THREAD

**Issue by whitewolf009** [EspoTek/Labrador#143] opened 2021-02-09 16:49 UTC
I am trying to open the labrador application on my macbook pro which is running the macos 11.2 big sur and the application is not responding 

UPDATE : 
I used the updated application it is working
but i am unable to calibrate the labrador even after following the steps correctly it always throws calibration abandoned due to out-of-range values error

**Comment by EspoTek** [comment] 2021-02-10 01:37
I'm closing this issue as it's a duplicate of https://github.com/EspoTek/Labrador/issues/131.

Regarding the out-of-range values error, please email me at admin@espotek.com and walk me through what you're doing (with screenshots where applicable).  We should be able to get to the bottom of the calibration issue that way.

Cheers,
~Chris

**Closed by EspoTek** 2021-02-10 01:37 UTC
