### ISSUE TITLE
Signal syncronization when pausing with trigger

### ISSUE THREAD

**Issue by drtrigon** [EspoTek/Labrador#51] opened 2018-09-02 16:38 UTC
I have the strong impression that when I pause the display of data or configure the trigger for single shot, the two signals from Oscilloscope CH1 and CH2 are not in sync. If I pause 10 times, about 9 times they are shifted by some time against each other. (Also the trigger seams not to be precise; t=0 does not seem to be the edge - no matter if pos or neg.)

**Comment by EspoTek** [comment] 2018-09-05 05:07
I am unable to reproduce this bug, and I can't think of a technical reason why it would exist.  Both CH1 and CH2 should come in the same packet, and neither channel should be updated except when the other one also is.

Are you able to reproduce this with CH1 and CH2 directly shorted to one another?  Perhaps it's a race condition.

**Comment by drtrigon** [comment] 2018-09-10 18:07
I did not short them but I only connected Ch1 and what you see on Ch2 is cross-talk, here an example of today:
![labrador-running](https://user-images.githubusercontent.com/18975831/45315449-c43c1980-b534-11e8-98be-2f693f589a4c.png)
![labrador-paused](https://user-images.githubusercontent.com/18975831/45315448-c3a38300-b534-11e8-88ec-e049e2a8febb.png)
... as you can see the spikes move with respect to the actual signal by an arbitrary amount of time. This was done using a trigger on Ch1. Actually when taking a closer look I think it is Ch1 that does get shifted - may it be related to using the trigger on that Ch?

**Comment by EspoTek** [comment] 2018-09-16 03:39
Whoops, this looks suspect:

```
    readData375_CH1 = internalBuffer375_CH1->readBuffer(window,GRAPH_SAMPLES,CH1_mode==2, delay + ((triggerEnabled&&!paused_CH1) ? triggerDelay + window/2 : 0));
    if(CH2_mode) readData375_CH2 = internalBuffer375_CH2->readBuffer(window,GRAPH_SAMPLES,CH2_mode==2, delay + (triggerEnabled ? triggerDelay + window/2 : 0));

```
Note the "TriggerEnabled" condition is different between the two channels!
I'll get a proper fix up shortly.

**Comment by EspoTek** [comment] 2018-09-16 04:14
I have just pushed a fix to this but am unable to test it right at the moment.  Are you able to confirm that it now works?

**Comment by drtrigon** [comment] 2018-09-16 08:06
Thanks! Yes I can confirm that both channels stay in sync now! When pausing both are moved now by the same amount of time. Nice would be if the don't move at all.

Is it possible that the trigger for "Ch1 (rising)" triggers the falling slope and vice-versa?

Also "AC Coupled" for Ch1 does not work - when I click it just pauses the measurement - interestingly in a correct manner (the channels are NOT moved at all and stay in sync). In order that AC coupling works I have to first click it on Ch2 and then on Ch1.

**Comment by EspoTek** [comment] 2018-09-17 09:15
Closing now.  Thanks again, Tigon.  :)

Regarding the AC Coupling, please open a separate issue with instructions to reproduce the bug.  I can't see what you see.

**Closed by EspoTek** 2018-09-17 09:15 UTC

**Comment by drtrigon** [comment] 2018-09-17 15:09
Done in https://github.com/EspoTek/Labrador/issues/55
