### ISSUE TITLE
Raspberry Pi 4 (updated Buster) installation terminated unsuccessfully

### ISSUE THREAD

**Issue by wwoofbum** [EspoTek/Labrador#212] opened 2022-02-28 22:32 UTC
After "Cloning into 'labrador'...
remote: Enumerating objects: 779, done.
.
.
Receiving objects 100% (779/779) ,  reused 662 (delta 197), pack-reused 0
Resolving deltas: 100% (209/209), done.
qmake could not find a Qt installation of ''
~$

[fullListing.txt](https://github.com/EspoTek/Labrador/files/8157337/fullListing.txt)

**Comment by bobhb** [comment] 2022-03-13 16:26
Same issue. Apparently systemic. Holding off on bad review at store. Chris, a bone please?   Thanks!!

**Comment by EspoTek** [comment] 2022-03-14 06:56
![Bone](https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Left_femur_of_extinct_elephant%2C_Alaska%2C_Ice_Age_Wellcome_L0057714.jpg/375px-Left_femur_of_extinct_elephant%2C_Alaska%2C_Ice_Age_Wellcome_L0057714.jpg)

I'll try and reproduce it tomorrow.  This is on Buster, right?

**Comment by EspoTek** [comment] 2022-03-14 07:38
Have reproduced it now.  Got the exact error you did, and it seems like a one-line fix I made to the bootstrap script has made the issue go away!

**Comment by EspoTek** [comment] 2022-03-14 07:51
Yep.  Looks like that did it.  Software successfully compiles and runs.  Could you please let me know if it fixed it from you end, then I can mark this one off as done!

**Comment by bobhb** [comment] 2022-03-14 11:58
Good one. Glad you found it!

**Comment by EspoTek** [comment] 2022-03-14 22:59
Awesome.  Marking as closed for now.  Please let us know if more issues pop up!

**Closed by EspoTek** 2022-03-14 22:59 UTC
